### ISSUE TITLE
Save button shows success before the PUT request is done

### ISSUE THREAD

**Issue by chuanqisun** [osmoscraft/osmosmemo#15]
Root cause: `inserContent` need to return the promise

https://github.com/osmoscraft/osmosmemo/blob/9569b4b9d87148ca2b072204180ef51f3f4cac82/src/lib/github/rest-api.ts#L11

**Comment by Debajyoti111** [comment]
@chuanqisun I have made PR #16  which should fix the issue. Please check and if possible, add the hactoberfest tag.

**Comment by chuanqisun** [comment]
Fixed in #17
