### ISSUE TITLE
Saved urls are lowercased

### ISSUE THREAD

**Issue by dinh** [osmoscraft/osmosmemo#3]
Url should be kept as is. Lowercasing breaks links like youtube links.

**Comment by chuanqisun** [comment]
Thanks, will be addressed in the next fix.

**Comment by chuanqisun** [comment]
v2.2.1 will contain the fix. 
- Firefox: live
- Chrome: under review (live in 1-2 days)
- Edge: under review (live in 7 days)

Big thank you again, @dinh, I realized a lot of my past youtube bookmarks are broken because of this issue.
