### ISSUE TITLE
View bookmarks from extension

### ISSUE THREAD

**Issue by srid** [osmoscraft/osmosmemo#9]
Can the browser extension be made to _display_ the current list of bookmarks as well? In addition to saving them.

**Comment by chuanqisun** [comment]
Hi @srid, how do you plan to use the full list, if it is available as part of the extension UI? Currently, the Search button opens the GitHub page that has the full list on it. GitHub does a good job formatting Markdown text and Ctrl+F is a good search solution, so I hope not to reimplement a Markdown renderer inside the extension. However, I'd love to learn more about the request so I can plan something as a future enhancement. 

Thanks for the feedback!

**Comment by chuanqisun** [comment]
Closed due to inactivity from OP. Feel free to reopen.
